"""update word unique contraint

Revision ID: 01eec39d089d
Revises: 14e7f3c9a24a
Create Date: 2021-11-10 15:11:13.925157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eec39d089d'
down_revision = '14e7f3c9a24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('words_title_key', 'words', type_='unique')
    op.create_unique_constraint('_title_dialect_uc', 'words', ['title', 'dialect'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_title_dialect_uc', 'words', type_='unique')
    op.create_unique_constraint('words_title_key', 'words', ['title'])
    # ### end Alembic commands ###
