"""add a col to fieldversion table

Revision ID: 49b42fade15b
Revises: 01eec39d089d
Create Date: 2021-11-11 08:49:19.454657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b42fade15b'
down_revision = '01eec39d089d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_versions', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_versions', 'active')
    # ### end Alembic commands ###
