"""adding work maanage info into word table

Revision ID: 59a15acddb37
Revises: 1ffc4aa537ad
Create Date: 2021-11-18 14:22:25.564733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a15acddb37'
down_revision = '1ffc4aa537ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('merged_by', sa.String(), nullable=True))
    op.add_column('words', sa.Column('merged_at', sa.DateTime(), nullable=True))
    op.add_column('words', sa.Column('locked_by', sa.String(), nullable=True))
    op.add_column('words', sa.Column('deactivated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'deactivated_by')
    op.drop_column('words', 'locked_by')
    op.drop_column('words', 'merged_at')
    op.drop_column('words', 'merged_by')
    # ### end Alembic commands ###
