"""add active col in word and suggestion tables

Revision ID: 7e85324c8d89
Revises: 49b42fade15b
Create Date: 2021-11-11 10:31:36.069990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e85324c8d89'
down_revision = '49b42fade15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('words', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'active')
    op.drop_column('suggestions', 'active')
    # ### end Alembic commands ###
